language: java

# Make NetworkTables happy
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8
      - oracle-java8-installer
      
install:
- "./gradlew build"
- "./gradlew generateExternalPatches"
- "./gradlew build"
- "./gradlew genMetrics"
- ruby tools/setup.rb
- ruby tools/inspector.rb
- ruby tools/imports.rb
- "./gradlew verify"
jdk:
- oraclejdk8
notifications:
  email: false
cards:
  enabled:
  - master
  - development
  title: Toast
