language: java
install:
- "./gradlew build"
- "./gradlew generateExternalPatches"
- "./gradlew build"
- "./gradlew genMetrics"
- ruby tools/setup.rb
- ruby tools/inspector.rb
- ruby tools/imports.rb
script:
- "./gradlew verify"
jdk:
- oraclejdk8
notifications:
  email: false
cards:
  enabled:
  - master
  - development
  title: Toast
