language: java

install:
  - "./gradlew wpi"
  - "./gradlew build"
  - "./gradlew generateExternalPatches"
  - "./gradlew build"

script:
  - "./gradlew verify"

jdk:
  - oraclejdk8

notifications:
  email: false
